### ISSUE TITLE
Temporal training takes much longer time than single-frame warmup epochs.

### ISSUE THREAD

**Issue by synsin0** [lucifer443/RecurrentBEV#3]
I train the 256x704 config with 8 L20 and finds that temporal training (after 6 epochs) takes much longer time than single-frame warmup epochs (before 6 epochs). I attach my training log here. Is that normal for this training speed?
[20241002_223820.log](https://github.com/user-attachments/files/17242026/20241002_223820.log)

**Comment by lucifer443** [comment]
It is normal for the temporal model to be slower because of the need to load and calculate historical information.
